"""FEAT-69 clean-pin receipts. Usage (from the FEAT-69 worktree root):
    python3 notes/receipt-scripts/feat69-cleanpin.py <pin-sha> <baseline-sha>
Creates (or reuses) detached checkouts under .claude/worktrees/harness/ for the pin and the baseline,
asserts both identities and `git status --porcelain` empty, runs feat69-baseline.py ONCE in each
(every measurement executed exactly once; every byte, hash, diff and verdict below derives from those
two executions), compares after replacing ONLY each checkout's absolute root with `<checkout>`, runs
feat69-grade-assert.py at the pin (green) and in the baseline checkout (red), and writes
notes/clean-pin-byte-receipts.generated.md carrying `implementation_pin: <full sha>`."""
import subprocess, sys, os, json, hashlib, datetime, difflib

ROOT = "/Users/molchairuangutai/GitHub/harness"
HERE = os.path.dirname(os.path.abspath(__file__))
pin, baseline = sys.argv[1], sys.argv[2]
WT = os.path.join(ROOT, ".claude/worktrees/harness")
pin_dir = os.path.join(WT, f"feat69-cleanpin-{pin}")
base_dir = os.path.join(WT, f"feat69-base-{baseline}")
for d, ref in ((pin_dir, pin), (base_dir, baseline)):
    if not os.path.isdir(d):
        subprocess.run(["git", "-C", ROOT, "worktree", "add", "--detach", d, ref], check=True, capture_output=True)
full = {}
for label, d, ref in (("pin", pin_dir, pin), ("baseline", base_dir, baseline)):
    full[label] = subprocess.check_output(["git", "-C", d, "rev-parse", "HEAD"], text=True).strip()
    assert full[label].startswith(ref), f"{label} checkout is at {full[label]}, not {ref}"
    assert not subprocess.check_output(["git", "-C", d, "status", "--porcelain"], text=True), f"{label} checkout is dirty"

started = datetime.datetime.now(datetime.UTC).isoformat(timespec="seconds")
runs = {}
for label, d in (("baseline", base_dir), ("pin", pin_dir)):
    out = f"/tmp/feat69-{label}-{full[label][:8]}.json"
    print(f"== {label} measurements in {d}", flush=True)
    subprocess.run([sys.executable, os.path.join(HERE, "feat69-baseline.py"), d, out], check=True)
    runs[label] = json.load(open(out))
finished = datetime.datetime.now(datetime.UTC).isoformat(timespec="seconds")

def norm(text, root):
    return text.replace(root, "<checkout>")

names = [k for k in runs["pin"] if k != "code_grade"]
rows, raw_diff = [], []
for n in names:
    b, p = runs["baseline"][n], runs["pin"][n]
    same = (b["exit"] == p["exit"] and norm(b["stdout"], base_dir) == norm(p["stdout"], pin_dir)
            and norm(b["stderr"], base_dir) == norm(p["stderr"], pin_dir))
    rows.append((n, b["exit"], p["exit"], b["stdout_sha"][:12], p["stdout_sha"][:12], b["stderr_sha"][:12], p["stderr_sha"][:12], same))
    for stream in ("stdout", "stderr"):
        bt, pt = norm(b[stream], base_dir), norm(p[stream], pin_dir)
        if bt != pt:
            raw_diff.append((f"{n} ({stream})", [l for l in difflib.unified_diff(bt.splitlines(), pt.splitlines(), lineterm="", n=0)
                                                 if l.startswith(("-", "+")) and not l.startswith(("---", "+++"))]))

env = dict(os.environ, FEAT69_BASELINE_JSON=f"/tmp/feat69-baseline-{full['baseline'][:8]}.json")
ASSERT = os.path.join(HERE, "feat69-grade-assert.py")
green = subprocess.run([sys.executable, ASSERT], cwd=pin_dir, capture_output=True, text=True, env=env)
red = subprocess.run([sys.executable, ASSERT], cwd=base_dir, capture_output=True, text=True)

out = [f"# FEAT-69 — clean-checkout implementation-pin receipts (GENERATED by receipt-scripts/feat69-cleanpin.py; do not edit)", "",
       f"implementation_pin: {full['pin']}", "",
       f"Written {finished} (measurements started {started}), AFTER the pin it names; this file and its commit are not inside the pin.", "",
       f"- implementation pin: `{full['pin']}`", f"- baseline: `{full['baseline']}` (the amended plan's baseline; origin/main when the worktree was cut)",
       f"- pin checkout: `{pin_dir}` (detached, `git status --porcelain` empty, asserted)",
       f"- baseline checkout: `{base_dir}` (detached, `git status --porcelain` empty, asserted)",
       "- one execution per measurement per checkout: `feat69-baseline.py <checkout> <json>` ran once in each; the JSONs are the only source of every byte, hash, diff and verdict here.",
       "- normalisation: each checkout's own absolute root replaced by `<checkout>`, on both sides, and nothing else. Every remaining difference is listed below verbatim and ruled in `notes/build-divergences.md`.", "",
       "## SC-02 measurements at the pin vs baseline", "",
       "| measurement | exit base→pin | stdout sha base / pin | stderr sha base / pin | identical (normalised) |", "|---|---|---|---|---|"]
for n, be, pe, bo, po, be_, pe_, same in rows:
    out.append(f"| `{n}` | {be}→{pe} | {bo} / {po} | {be_} / {pe_} | {'yes' if same else '**NO**'} |")
out += ["", f"All identical (normalised): **{'yes' if all(r[-1] for r in rows) else 'NO'}** ({sum(r[-1] for r in rows)}/{len(rows)}).", "",
        "### Differences after the one normalisation, exact lines", ""]
for n, lines in raw_diff:
    out += [f"`{n}`:", "```"] + lines + ["```", ""]
if not raw_diff:
    out += ["none", ""]
out += ["## SC-01: feat69-grade-assert.py at the pin (with the baseline record for moved/new classification) — green", "",
        f"run in the pin checkout → exit {green.returncode}", "```", (green.stdout + green.stderr).rstrip(), "```", "",
        "## SC-01 red-first: the same assertion in the baseline checkout — red", "",
        f"run in the baseline checkout → exit {red.returncode}", "```", (red.stdout + red.stderr).rstrip(), "```", "",
        "## code_grade records (from the same two executions)", ""]
for label in ("baseline", "pin"):
    g = runs[label]["code_grade"]
    out += [f"- {label}: {len(g['functions'])} function(s) over {g['files']}; below bar 4: "
            f"{[(f['qualname'], f['grade']) for f in g['functions'] if f['grade'] < 4]}"]
path = os.path.join(os.path.dirname(HERE), "clean-pin-byte-receipts.generated.md")
open(path, "w", encoding="utf-8").write("\n".join(out) + "\n")
print("\n".join(out))
