import subprocess, json, sys, hashlib
root = sys.argv[1]; out = sys.argv[2]
suites = ['tests/integration/test-anchor-directions.py', 'tests/integration/test-bash-write-guard.py', 'tests/integration/test-board-lifecycle.py', 'tests/integration/test-branch-create-gate.py', 'tests/integration/test-check-domain-approval.py', 'tests/integration/test-check-domain-artifact.py', 'tests/integration/test-check-domain-claims.py', 'tests/integration/test-check-domain-grant.py', 'tests/integration/test-check-domain-post.py', 'tests/integration/test-check-domain-worktree-parity.py', 'tests/integration/test-check-domain-worktree.py', 'tests/integration/test-check-domain.py', 'tests/integration/test-check-plan-routes.py', 'tests/integration/test-check-state-entry.py', 'tests/integration/test-check-state-feat59.py', 'tests/integration/test-check-state-handoff.py', 'tests/integration/test-check-state-inv26.py', 'tests/integration/test-check-state-plans.py', 'tests/integration/test-check-state-records.py', 'tests/integration/test-check-state-table.py', 'tests/integration/test-check-state-worktrees.py', 'tests/integration/test-check-state.py', 'tests/integration/test-factory-integration.py', 'tests/integration/test-factory-issue-types.py', 'tests/integration/test-feature-worktree.py', 'tests/integration/test-gen-decisions-index.py', 'tests/integration/test-gh-close-gate.py', 'tests/integration/test-gh-sync-abandon.py', 'tests/integration/test-gh-sync-open.py', 'tests/integration/test-gh-sync-record.py', 'tests/integration/test-gh-sync-ship.py', 'tests/integration/test-gh-sync-start-task.py', 'tests/integration/test-harness-yaml.py', 'tests/integration/test-inflight-registry.py', 'tests/integration/test-inject-expertise.py', 'tests/integration/test-layout-migration.py', 'tests/integration/test-plan-merge.py', 'tests/integration/test-plan-sign-gate.py', 'tests/integration/test-plan-team.py', 'tests/integration/test-post-merge-sweep.py', 'tests/integration/test-run-unit-tests-kinds.py', 'tests/integration/test-run-unit-tests-layout.py', 'tests/integration/test-validate-digest.py', 'tests/integration/test-validate-feature-json.py', 'tests/integration/test-worktree-terminal.py', 'tests/unit/test-artifact-accessors.py', 'tests/unit/test-config-shape-matrix.py', 'tests/unit/test-factory-claim.py', 'tests/unit/test-factory-config.py', 'tests/unit/test-factory-workspace.py', 'tests/unit/test-gh-board.py', 'tests/unit/test-gh-cost-log.py', 'tests/unit/test-handoff-done-when.py', 'tests/unit/test-harness-boundary.py', 'tests/unit/test-no-distribution.py', 'tests/unit/test-suite-independence.py', 'tests/unit/test-wayfind.py']
res = {}
for s in suites:
    p = subprocess.run([sys.executable, s], cwd=root, capture_output=True, text=True, timeout=1800)
    res[s] = {"exit": p.returncode, "stdout_sha": hashlib.sha1(p.stdout.encode()).hexdigest(), "stderr_sha": hashlib.sha1(p.stderr.encode()).hexdigest(), "stdout": p.stdout, "stderr": p.stderr}
    print(f"{p.returncode:3} {s} out={len(p.stdout)}B err={len(p.stderr)}B")
json.dump(res, open(out, "w"))
